#!/bin/sh

export RSYNC_PASSWORD=codi

rsync -a kodi@zeta.upv.es::kodi/pelisalacarta/python/main-classic/ \
         /cygdrive/c/Users/prosich.UPVNET/AppData/Roaming/Kodi/addons/plugin.video.pelisalacarta

