#!/bin/sh
PATH=/soft/scripts:$PATH
KODI=`kodidir`
export RSYNC_PASSWORD=codi

rsync -a --delete \
  kodi@zeta.upv.es::kodi/pelisalacarta/python/main-classic/ \
  $KODI/addons/plugin.video.pelisalacarta

